### ISSUE TITLE
FirebaseMessaging integration

### ISSUE THREAD

**Issue by figueiredorui** [FilledStacks/flutter-architecture-skeletons#1]
I like your scopemodel architecture. 
I have a question regarding integrating with the FirebaseMessaging  plugin. 
My app receives push data notifications and I want to update the model with data received.
Where would be the best place to have the following configure implementation.

```
_firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) {
      // update model
      },
      onResume: (Map<String, dynamic> message) {
      // update model
      },
      onLaunch: (Map<String, dynamic> message) {
      // update model
      },
    );

```

**Comment by FilledStacks** [comment]
Hi thanks for checking out the repo,

It depends. There's two scenarios.

**Only update data**
If you just want to update a singleton model with data when it comes through you can register in the main.dart file in your App.

That way in your onMessage you can update the service your model uses with data and retrieve it through the model. Something like below.

```dart
// onMessage in the configure
var service = locator<PushNotificationService>();
service.updateData(message);

...

// In the model

Map<String, dynamic> get pushData => service.updatedData;

```

**Navigate when data is received**
If you want to navigate when push data is received then it has to be where you have access to a context that can navigate. Usually the first view that's displayed (one that's always alive). [See this question I answered on SO](https://stackoverflow.com/a/54741982/1463174).

Something like below. If you're unfamiliar with why I'm using a service [I show in this video](https://youtu.be/qa6A2TOqY0A) how I use the architecture and keep the logic separate from the model itself. It's a short one so you should get the idea.

**Comment by figueiredorui** [comment]
Hi Dane,
Thanks for the guidance provided.
I'm going to take the same approach as in your Realtime Stats monitor example.

Now,  imagine that you have two stats views (HomeView and HomeDetailView), would you use the same model (HomeViewModel)  and would you register it as a singleton?

Also, on the scenarios where you load the data from an API the first time you navigate to a certain view (onModelReady) but you don't want to reload that data the second time o came back to the view, would you register the Model has singleton as well?

Thanks,
Rui

**Comment by FilledStacks** [comment]
@figueiredorui The way the architecture is setup is to use a Model per View. That's the way that I've implemented it and use it. I would use a model for a different view when it has literally the exact same code in the model for the other view. If it doesn't I would create a new model instead.

Your stats/data would come from your service so as long as that's a singleton you can use it in both models and get the same data for both. 

> you don't want to reload that data the second time

You'll still call your async function in there and direct the call to the service. Inside the service you'll check if your data you want is null, if it is you run the code again. If it's not then you just skip the code so the request won't happen again. Or you can use a `bool  hasFetchedData` flag. That way your code in the view stays the same, it doesn't care if if has made the request or not, it just runs the same code when the model is ready. Your service determines if it goes through or not.

The way I've set it up here is to make sure that most of the business logic happens in the services and the models only reduce state for the UI. I do it that way because it becomes kind of universal for all architectures. You don't even need an "architecture". With the correct coding principles and code separation you can have a healthy code base that's easy to maintain.

**Comment by figueiredorui** [comment]
That makes sense. 
Thanks

**Comment by FilledStacks** [comment]
Happy that I could help :)
